name: whisper-app
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11.11
  - pip=24.3.1
  - pip:
    - --extra-index-url https://download.pytorch.org/whl/cu118
    - torch==2.5.1+cu118
    - torchaudio==2.5.1
    - transformers==4.47.1
    - accelerate==1.2.1
    - ffmpeg==1.4
    - python-ffmpeg==2.0.12
    - flask==3.1.0
    - flask-restx==1.3.0
    - SQLAlchemy==2.0.36
    - python-dotenv==1.0.1

    # For dev only
    - ipywidgets==8.1.5
    - ipykernel==6.29.5
    - flask-cors==5.0.0
